### ISSUE TITLE
How to trigger the autopromote functionality?

### ISSUE THREAD

**Issue by individualae** [eventespresso/eea-wait-lists#1]
How can I tap into the autopromote functionality? Now it's triggered when an event is updated. How can I access that functionality?

**Comment by tn3rb** [comment]
Not sure exactly what you want to do since your question is somewhat vague...
but everything related  to auto-promotion happens in `EventEspresso\WaitList\domain\services\commands\PromoteWaitListRegistrantsCommandHandler::autoPromoteRegistrations()`.

There is an action  hook at the end of that method that you could use to "tap into" that process:

`'AHEE__EventEspresso_WaitList_domain_services_commands_PromoteWaitListRegistrantsCommandHandler__autoPromoteRegistrations'`

Hope that helps
