### ISSUE TITLE
Enhancement: move on to next attendee on wait list after a period of time

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-wait-lists#10]
When we sent out the Wait List Manager announcement email a few weeks ago, we encouraged members to reply back to we could help with questions.

A common question that we saw was a variation of these:

- What if the next person on the waitlist doesn't do anything?
- Does the Wait List Manager move to someone else after a while?

Since then, I've seen more questions like that: https://secure.helpscout.net/conversation/657831827/564339?folderId=100617

I think this would be a valuable addition to the Wait List Manager since we have ongoing requests about it and I'd like to help plan out this enhancement.

**Comment by sethshoultes** [comment]
@tn3rb how long would it take you to add this functionality?

**Comment by tn3rb** [comment]
## questions

@sethshoultes @garthkoyle @lorenzocaum && @joshfeck 

- Do we want this to apply to **ALL** registrations that are promoted from the Wait List or only to those that are auto-promoted?
- What should happen to promoted registrations after the time limit expires? Should they be demoted back to the Wait List status (RWL) or cancelled (RCN)?
- Should we add an additional admin option for selecting what status is applied after demotion?
- Should an email be sent out to promoted registrants if their time limit expires and they are demoted ?

## required steps and estimates

- (2 hours) add new input to `EventEditorWaitListMetaBoxForm` for setting the duration for the "Wait List Promotion Time Limit" (open for better name suggestions). Might work best as a dropdown with the following options (also open for suggestions):
    - 2 hours
    - 6 hours
    - 12 hours
    - 1 day
    - 2 days
    - 1 week
    - no limit
- **(optional)** (2 hours) add new input to `EventEditorWaitListMetaBoxForm` for setting what happens to promoted registrations after the time limit expires. Might work best as a dropdown with the following options (open for suggestions):
    - leave Registrations as is but promote additional Wait List Registrants `*`
    - set Registration status back to Wait List
    - set Registration status to Cancelled
    - `*` = would need to demote registrations that were promoted to Approved down to Pending Payment
- (4 hours) Create new `WaitListCronJobHandler` class and add new method called something like `revokeWaitListPromotion()` plus its corresponding methods for setting up the schedule, etc, that would demote specified registrations back to 
- (1 hour) add logic to `WaitList::after_registration()` for loading the new `WaitListCronJobHandler` class so that cron jobs can be registered immediately (may need to load even earlier depending on how WP core is setup)
- **If ONLY applying to Auto-Promotions** then:
    - (1 hour) trigger `revokeWaitListPromotion()` in `PromoteWaitListRegistrantsCommandHandler::autoPromoteRegistrations()` after each registration status is upgraded
- else **If applying to ALL Wait List Promotions** then:
    - (1 hour) hook into `AHEE__EE_Registration__set_status__after_update` and trigger `revokeWaitListPromotion()` from new action callback
- **(optional)** add new email to be sent out to promoted registrants if their time limit expires and they are demoted

@nerrad 
can you plz provide an estimate for adding a new email that is sent out after auto-demotion?

**Comment by nerrad** [comment]
I edited your comment and added an estimate.  An additional thing I'm going to comment on is that we have to keep in mind the flakiness of wp-cron.  However, for this use-case its probably going to be okay if things aren't _exactly_ on schedule.

**Comment by nerrad** [comment]
Oh also, my estimate is just for doing the development for the new email notification.  It does not include full testing or creating any automated tests.

**Comment by joshfeck** [comment]
I'm wary of adding this feature because it adds a lot of complexity. Also, we've learned (from the switch to generating messages on a separate request) how unreliable wp_cron can be. Some hosts even turn it off! Will this feature even work on a lot of shared hosts? For example, many times we end up advising the end user to switch the messages setting to "Send on same request". Will this feature have a fallback mechanism for sites where wp_cron isn't functional?

On the other hand, what about wait lists per datetime? That seems to be the most requested feature since wait lists was released.

**Comment by tn3rb** [comment]
### Re: the unreliability of WP_Cron

I think the only option in terms of a fallback would be to build our own scheduling system that works similarly to `WP_Cron`. Not an ideal scenario but there isn't really any other choice if hosts and/or users are going to disable existing core functionality. Actually that isn't really true as we **could** display a notice in the admin to indicate that a feature won't work if `WP_Cron` is disabled and recommend that they contact their host regarding turning that functionality on and/or change hosts if that is not possible.


@joshfeck 
> re:  what about wait lists per datetime?

well if you are wary of adding cron-like functionality because it adds a lot of complexity, then you should be wary of wait lists per datetime because that is even more complex. That said, I don't think we should shy away from things simply on the basis of them being complex, but **should** take some steps to try and communicate to users that super cheap hosting is not going to cut the mustard if they want to enable complex features and/or everything and the kitchen sink.
